Add support for string concatenation in keys
yellowblood/hocon-js pull request #8
Opened 2017-03-19 13:31 UTC by gillyb

2017-03-19 16:16 UTC, yellowblood requested changes

2017-03-19 16:16 UTC, yellowblood commented on hoconjs.js
> +                console.log('adding to key : ' + c);
Remove :)

2017-03-19 16:16 UTC, yellowblood commented on tests.js
> +  console.log(JSON.stringify(obj));
Remove

2017-03-19 16:16 UTC, yellowblood commented on tests.js
> +  }`);
Sadly our phantomJS build doesn't support ES6, either convert to ES5 or add a build step that does it in Travis

2017-03-20 06:27 UTC, gillyb commented on hoconjs.js
> +                console.log('adding to key : ' + c);
Oh shit! didn't mean to leave these of course!

2017-03-20 06:28 UTC, gillyb commented on tests.js
> +  }`);
oh, bummer.. ok, might add the build step in the future, for now i'll fix the code.

2017-03-20 06:31 UTC, gillyb commented
@yellowblood I updated the code, just take a look now, and merge if ok

2017-03-20 07:05 UTC, yellowblood approved these changes

2017-03-20 07:05 UTC, merged